//! Value-pinned tests for the dynamic-fee FSM (`dynamic_fee` module).
//!
//! Expected values were generated by an independent Python re-implementation
//! of the upstream `commons/src/extensions/lb_pair.rs` algorithms — the
//! pinned integers catch porting mistakes the way a round-trip through the
//! function under test cannot.
//!
//! The pool parameters mirror a realistic bin_step=25 Meteora preset
//! (SOL/USDC-style): base_factor 10_000, filter 30s, decay 600s,
//! reduction_factor 5_000 (50%), variable_fee_control 40_000,
//! max_volatility_accumulator 350_000, protocol_share 500 (5%).

use solana_dlmm_meteora::{
    advance_active_bin, compute_fee, compute_fee_from_amount, compute_protocol_fee,
    compute_variable_fee, fee_on_input, get_base_fee, get_total_fee, is_support_limit_order,
    update_references, update_volatility_accumulator, ErrorCode, PoolView, StaticParameters,
    VariableParameters, MAX_BIN_ID, MIN_BIN_ID,
};

fn preset() -> PoolView {
    PoolView {
        active_id: -1000,
        bin_step: 25,
        has_rewards: false,
        parameters: StaticParameters {
            base_factor: 10_000,
            filter_period: 30,
            decay_period: 600,
            reduction_factor: 5_000,
            variable_fee_control: 40_000,
            max_volatility_accumulator: 350_000,
            min_bin_id: -436_704,
            max_bin_id: 436_704,
            protocol_share: 500,
            base_fee_power_factor: 0,
            function_type: 0,
            collect_fee_mode: 0,
        },
        v_parameters: VariableParameters {
            volatility_accumulator: 0,
            volatility_reference: 0,
            index_reference: 0,
            last_update_timestamp: 0,
        },
    }
}

#[test]
fn fee_rates_on_quiet_pool() {
    // acc = 0: variable fee vanishes, total fee is the base fee.
    // base_fee = base_factor * bin_step * 10 = 10_000 * 25 * 10 = 2_500_000
    // (0.25% in FEE_PRECISION = 1e9 units).
    let pool = preset();
    assert_eq!(get_base_fee(&pool).unwrap(), 2_500_000);
    assert_eq!(compute_variable_fee(&pool, 0).unwrap(), 0);
    assert_eq!(get_total_fee(&pool).unwrap(), 2_500_000);
    // Gross-up (ceil) vs contained-fee (ceil) round differently.
    assert_eq!(compute_fee(&pool, 1_000_000).unwrap(), 2_507);
    assert_eq!(compute_fee_from_amount(&pool, 1_000_000).unwrap(), 2_500);
    // Protocol share 5%, floor.
    assert_eq!(compute_protocol_fee(&pool, 2_503).unwrap(), 125);
}

#[test]
fn variable_fee_at_volatility() {
    // acc = 50_000 (5 bins crossed at BASIS_POINT_MAX granularity):
    // variable_fee = ceil(40_000 * (50_000 * 25)^2 / 1e11) = 625_000.
    let mut pool = preset();
    pool.v_parameters.volatility_accumulator = 50_000;
    assert_eq!(compute_variable_fee(&pool, 50_000).unwrap(), 625_000);
    assert_eq!(get_total_fee(&pool).unwrap(), 3_125_000);
    assert_eq!(compute_fee(&pool, 1_000_000).unwrap(), 3_135);
    assert_eq!(compute_fee_from_amount(&pool, 1_000_000).unwrap(), 3_125);
}

#[test]
fn base_fee_power_factor_scales_and_total_fee_caps() {
    // base_fee_power_factor = 2 → base fee × 100 = 250_000_000, above the
    // 10% MAX_FEE_RATE cap; total fee must clamp to 100_000_000.
    let mut pool = preset();
    pool.parameters.base_fee_power_factor = 2;
    assert_eq!(get_base_fee(&pool).unwrap(), 250_000_000);
    assert_eq!(get_total_fee(&pool).unwrap(), 100_000_000);
}

#[test]
fn fee_at_max_volatility_accumulator() {
    // At the accumulator cap the variable fee is large but total stays
    // below MAX_FEE_RATE for this preset.
    let mut pool = preset();
    pool.v_parameters.volatility_accumulator = 350_000;
    assert_eq!(compute_variable_fee(&pool, 350_000).unwrap(), 30_625_000);
    assert_eq!(get_total_fee(&pool).unwrap(), 33_125_000);
    assert_eq!(compute_fee(&pool, 1_000_000).unwrap(), 34_260);
}

#[test]
fn update_references_three_branches() {
    let base = {
        let mut p = preset();
        p.v_parameters.volatility_accumulator = 100_000;
        p.v_parameters.volatility_reference = 7;
        p.v_parameters.index_reference = -990;
        p.v_parameters.last_update_timestamp = 1_000;
        p
    };

    // elapsed < filter_period: high-frequency window, nothing changes.
    let mut p = base;
    update_references(&mut p, 1_029).unwrap();
    assert_eq!(p.v_parameters.index_reference, -990);
    assert_eq!(p.v_parameters.volatility_reference, 7);

    // filter_period <= elapsed < decay_period: reference decays by
    // reduction_factor (50% of 100_000 = 50_000) and index snaps to active.
    let mut p = base;
    update_references(&mut p, 1_030).unwrap();
    assert_eq!(p.v_parameters.index_reference, -1_000);
    assert_eq!(p.v_parameters.volatility_reference, 50_000);

    // elapsed >= decay_period: reference zeroes.
    let mut p = base;
    update_references(&mut p, 1_600).unwrap();
    assert_eq!(p.v_parameters.index_reference, -1_000);
    assert_eq!(p.v_parameters.volatility_reference, 0);
}

#[test]
fn volatility_accumulator_accumulates_and_caps() {
    // 3 bins from the reference: acc = 25_000 + 3 * 10_000 = 55_000.
    let mut pool = preset();
    pool.v_parameters.volatility_reference = 25_000;
    pool.v_parameters.index_reference = -1_000;
    pool.active_id = -1_003;
    update_volatility_accumulator(&mut pool).unwrap();
    assert_eq!(pool.v_parameters.volatility_accumulator, 55_000);

    // 340_000 + 2 * 10_000 = 360_000 clamps to max_volatility_accumulator.
    let mut pool = preset();
    pool.v_parameters.volatility_reference = 340_000;
    pool.v_parameters.index_reference = -1_000;
    pool.active_id = -1_002;
    update_volatility_accumulator(&mut pool).unwrap();
    assert_eq!(pool.v_parameters.volatility_accumulator, 350_000);
}

#[test]
fn swap_shaped_fsm_sequence() {
    // The orchestrator's call pattern for a 3-bin crossing: references
    // update once (decay window: vol_ref = 60_000 * 50% = 30_000), then the
    // accumulator updates before each bin and the active id advances after.
    let mut pool = preset();
    pool.v_parameters.volatility_accumulator = 60_000;
    pool.v_parameters.index_reference = -1_000;
    pool.v_parameters.last_update_timestamp = 10_000;
    update_references(&mut pool, 10_100).unwrap();
    assert_eq!(pool.v_parameters.volatility_reference, 30_000);
    assert_eq!(pool.v_parameters.index_reference, -1_000);

    let mut fees = vec![];
    for _ in 0..3 {
        update_volatility_accumulator(&mut pool).unwrap();
        fees.push(get_total_fee(&pool).unwrap());
        advance_active_bin(&mut pool, true).unwrap();
    }
    // Fee climbs as bins are crossed: the dynamic-fee mechanism in action.
    assert_eq!(fees, vec![2_725_000, 2_900_000, 3_125_000]);
    assert_eq!(pool.v_parameters.volatility_accumulator, 50_000);
    assert_eq!(pool.active_id, -1_003);
}

#[test]
fn advance_active_bin_bounds() {
    let mut pool = preset();
    pool.active_id = MIN_BIN_ID;
    assert_eq!(
        advance_active_bin(&mut pool, true).unwrap_err(),
        ErrorCode::InsufficientLiquidity,
    );
    // The failed advance must not move the active bin.
    assert_eq!(pool.active_id, MIN_BIN_ID);

    pool.active_id = MAX_BIN_ID;
    assert_eq!(
        advance_active_bin(&mut pool, false).unwrap_err(),
        ErrorCode::InsufficientLiquidity,
    );

    pool.active_id = 0;
    advance_active_bin(&mut pool, true).unwrap();
    assert_eq!(pool.active_id, -1);
    advance_active_bin(&mut pool, false).unwrap();
    assert_eq!(pool.active_id, 0);
}

#[test]
fn limit_order_support_and_fee_mode_flags() {
    // function_type 0 (Undetermined): support iff no rewards configured.
    let mut pool = preset();
    assert!(is_support_limit_order(&pool));
    pool.has_rewards = true;
    assert!(!is_support_limit_order(&pool));

    // 1 = LiquidityMining: never. 2 = LimitOrder: always. Invalid: never.
    pool.parameters.function_type = 1;
    pool.has_rewards = false;
    assert!(!is_support_limit_order(&pool));
    pool.parameters.function_type = 2;
    pool.has_rewards = true;
    assert!(is_support_limit_order(&pool));
    pool.parameters.function_type = 3;
    assert!(!is_support_limit_order(&pool));

    // collect_fee_mode 0 (InputOnly): fee on input both directions.
    // 1 (OnlyY): fee lands on the Y side — output side when swapping X→Y.
    // Invalid byte defaults to fee-on-input (upstream behavior).
    let mut pool = preset();
    assert!(fee_on_input(&pool, true));
    assert!(fee_on_input(&pool, false));
    pool.parameters.collect_fee_mode = 1;
    assert!(!fee_on_input(&pool, true));
    assert!(fee_on_input(&pool, false));
    pool.parameters.collect_fee_mode = 2;
    assert!(fee_on_input(&pool, true));
    assert!(fee_on_input(&pool, false));
}
