//! Mainnet-replay fixture (milestone 6, DESIGN.md test layer 3).
//!
//! Real pool state captured from mainnet via public RPC
//! (`api.mainnet-beta.solana.com`) on 2026-07-21:
//! the Meteora DLMM SOL-USDC pair `HTvjzsfX3yU6BUodCjZ5vZkUrAxMDTrBs3CJaq43ashR`
//! (bin_step 1, the pair upstream's own integration tests use), LbPair
//! account + the three bin arrays around the active bin, trimmed to
//! ±25 bins. Expected outputs pinned by the independent Python oracle
//! over the captured state — NOT by replaying an on-chain transaction
//! (byte-exact tx replay arrives with the litesvm differential in v0.3).
//!
//! Generated by `capture_fixture.py`; do not edit the numbers by hand.

use solana_dlmm_meteora::{
    compute_swap_full, compute_swap_full_exact_out, BinView, PoolView, StaticParameters,
    VariableParameters,
};

/// 120s after the captured `last_update_timestamp` — a realistic quote gap
/// (outside the filter period, inside nothing in particular).
const NOW: i64 = 1784643101;

fn pool() -> PoolView {
    PoolView {
        active_id: -25466,
        bin_step: 1,
        has_rewards: false,
        parameters: StaticParameters {
            base_factor: 10000,
            filter_period: 10,
            decay_period: 120,
            reduction_factor: 5000,
            variable_fee_control: 2000000,
            max_volatility_accumulator: 100000,
            min_bin_id: -436704,
            max_bin_id: 436704,
            protocol_share: 1000,
            base_fee_power_factor: 0,
            function_type: 0,
            collect_fee_mode: 0,
        },
        v_parameters: VariableParameters {
            volatility_accumulator: 37905,
            volatility_reference: 7905,
            index_reference: -25469,
            last_update_timestamp: 1784642981,
        },
    }
}

#[rustfmt::skip]
fn bins() -> Vec<BinView> {
    vec![
    BinView { bin_id: -25491, amount_x: 0, amount_y: 336938749, price: 1441833155233955132, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25490, amount_x: 0, amount_y: 323990903, price: 1441977338549478528, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25489, amount_x: 0, amount_y: 318934433, price: 1442121536283333475, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25488, amount_x: 0, amount_y: 313889660, price: 1442265748436961809, limit_order_ask_side: 0, open_order_amount: 38841465, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25487, amount_x: 0, amount_y: 365495135, price: 1442409975011805505, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25486, amount_x: 0, amount_y: 356283287, price: 1442554216009306686, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25485, amount_x: 0, amount_y: 346453849, price: 1442698471430907616, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25484, amount_x: 0, amount_y: 336657076, price: 1442842741278050707, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25483, amount_x: 0, amount_y: 329510472, price: 1442987025552178512, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25482, amount_x: 0, amount_y: 370465669, price: 1443131324254733730, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25481, amount_x: 0, amount_y: 364510904, price: 1443275637387159204, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25480, amount_x: 0, amount_y: 355667794, price: 1443419964950897920, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25479, amount_x: 0, amount_y: 387365196, price: 1443564306947393010, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25478, amount_x: 0, amount_y: 378331502, price: 1443708663378087749, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25477, amount_x: 0, amount_y: 369301523, price: 1443853034244425558, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25476, amount_x: 0, amount_y: 361715026, price: 1443997419547850000, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25475, amount_x: 0, amount_y: 413485268, price: 1444141819289804785, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25474, amount_x: 0, amount_y: 404469687, price: 1444286233471733766, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25473, amount_x: 0, amount_y: 393312230, price: 1444430662095080939, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25472, amount_x: 0, amount_y: 368852616, price: 1444575105161290448, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25471, amount_x: 0, amount_y: 401858088, price: 1444719562671806577, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25470, amount_x: 0, amount_y: 417913608, price: 1444864034628073757, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25469, amount_x: 0, amount_y: 411508642, price: 1445008521031536565, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25468, amount_x: 0, amount_y: 399146883, price: 1445153021883639719, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25467, amount_x: 4519531716, amount_y: 35205763, price: 1445297537185828083, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25466, amount_x: 4880720041, amount_y: 0, price: 1445442066939546665, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25465, amount_x: 4810266699, amount_y: 0, price: 1445586611146240620, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25464, amount_x: 4800750921, amount_y: 0, price: 1445731169807355244, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25463, amount_x: 4667722891, amount_y: 0, price: 1445875742924335980, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25462, amount_x: 4730883269, amount_y: 0, price: 1446020330498628414, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25461, amount_x: 4798383481, amount_y: 0, price: 1446164932531678276, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25460, amount_x: 4865830035, amount_y: 0, price: 1446309549024931444, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25459, amount_x: 4687943713, amount_y: 0, price: 1446454179979833937, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25458, amount_x: 4363945136, amount_y: 0, price: 1446598825397831921, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25457, amount_x: 4431189996, amount_y: 0, price: 1446743485280371704, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25456, amount_x: 4494069703, amount_y: 0, price: 1446888159628899741, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25455, amount_x: 3819174870, amount_y: 0, price: 1447032848444862631, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25454, amount_x: 3913962003, amount_y: 0, price: 1447177551729707118, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25453, amount_x: 3939486037, amount_y: 0, price: 1447322269484880088, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25452, amount_x: 3895372309, amount_y: 0, price: 1447467001711828576, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25451, amount_x: 4142180806, amount_y: 0, price: 1447611748411999759, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25450, amount_x: 4388940006, amount_y: 0, price: 1447756509586840959, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25449, amount_x: 2624151561, amount_y: 0, price: 1447901285237799644, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25448, amount_x: 2732200420, amount_y: 0, price: 1448046075366323424, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25447, amount_x: 2027330420, amount_y: 0, price: 1448190879973860056, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25446, amount_x: 2132870924, amount_y: 0, price: 1448335699061857442, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25445, amount_x: 1919026825, amount_y: 0, price: 1448480532631763628, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25444, amount_x: 2012146240, amount_y: 0, price: 1448625380685026804, limit_order_ask_side: 1, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25443, amount_x: 2125348837, amount_y: 0, price: 1448770243223095307, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25442, amount_x: 2114112925, amount_y: 0, price: 1448915120247417617, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    BinView { bin_id: -25441, amount_x: 2221858430, amount_y: 0, price: 1449060011759442358, limit_order_ask_side: 0, open_order_amount: 0, processed_order_remaining_amount: 0 },
    ]
}

#[test]
fn replay_x_to_y_1000000000() {
    // 1 SOL -> USDC
    let quote = compute_swap_full(&pool(), &bins(), 1000000000, true, NOW).unwrap();
    assert_eq!(quote.amount_out, 78337172);
    assert_eq!(quote.fee, 105305);
    assert_eq!(quote.protocol_fee, 10529);
    assert_eq!(quote.pool_after.active_id, -25468);
    assert_eq!(quote.pool_after.v_parameters.volatility_accumulator, 20000);
}
#[test]
fn replay_x_to_y_5000000000() {
    // 5 SOL -> USDC
    let quote = compute_swap_full(&pool(), &bins(), 5000000000, true, NOW).unwrap();
    assert_eq!(quote.amount_out, 391670938);
    assert_eq!(quote.fee, 537305);
    assert_eq!(quote.protocol_fee, 53729);
    assert_eq!(quote.pool_after.active_id, -25468);
    assert_eq!(quote.pool_after.v_parameters.volatility_accumulator, 20000);
}
#[test]
fn replay_y_to_x_100000000() {
    // 100 USDC -> SOL
    let quote = compute_swap_full(&pool(), &bins(), 100000000, false, NOW).unwrap();
    assert_eq!(quote.amount_out, 1276073238);
    assert_eq!(quote.fee, 10000);
    assert_eq!(quote.protocol_fee, 1000);
    assert_eq!(quote.pool_after.active_id, -25466);
    assert_eq!(quote.pool_after.v_parameters.volatility_accumulator, 0);
}

#[test]
fn replay_exact_out_100_usdc() {
    let quote = compute_swap_full_exact_out(&pool(), &bins(), 100_000_000, true, NOW).unwrap();
    assert_eq!(quote.amount_in, 1276546351);
    assert_eq!(quote.fee, 135172);
    assert_eq!(quote.protocol_fee, 13516);
}
