//! Value-pinned tests for the multi-bin orchestrator (`swap_full` module).
//!
//! Expected values were generated by an independent Python re-implementation
//! of the upstream `commons/src/quote.rs` quote path (per-bin fills, fee
//! split, exact-in / exact-out orchestration) — never by running the Rust
//! functions under test.
//!
//! Pool: bin_step=100 (1%), base_factor 10_000 (1% base fee),
//! variable_fee_control 40_000, protocol_share 500 (5%),
//! filter 30s / decay 600s / reduction 5_000. Bins hold liquidity in
//! 1_000_000-unit blocks; bin prices come from `get_price_from_id`
//! (price at bin 100 ≈ 2.7048).

use solana_dlmm_meteora::{
    compute_swap_full, compute_swap_full_exact_out, get_price_from_id, BinView, ErrorCode,
    PoolView, StaticParameters, VariableParameters,
};

const B: u64 = 1_000_000;

fn preset(function_type: u8, collect_fee_mode: u8) -> PoolView {
    PoolView {
        active_id: 100,
        bin_step: 100,
        has_rewards: false,
        parameters: StaticParameters {
            base_factor: 10_000,
            filter_period: 30,
            decay_period: 600,
            reduction_factor: 5_000,
            variable_fee_control: 40_000,
            max_volatility_accumulator: 350_000,
            min_bin_id: -443_636,
            max_bin_id: 443_636,
            protocol_share: 500,
            base_fee_power_factor: 0,
            function_type,
            collect_fee_mode,
        },
        v_parameters: VariableParameters {
            volatility_accumulator: 0,
            volatility_reference: 0,
            index_reference: 0,
            last_update_timestamp: 0,
        },
    }
}

/// MM-only bin at its stored (initialized) price.
fn bin(bin_id: i32, amount_x: u64, amount_y: u64) -> BinView {
    BinView {
        bin_id,
        amount_x,
        amount_y,
        price: get_price_from_id(bin_id, 100).unwrap(),
        ..BinView::default()
    }
}

#[test]
fn exact_in_single_bin() {
    // 1_000_000 X into a deep bin: 1% fee on input (10_000), the rest
    // converts at the bin price. Active bin does not advance; the
    // volatility accumulator stays 0 (active == reference).
    let pool = preset(1, 0);
    let bins = [bin(100, 5 * B, 5 * B)];
    let quote = compute_swap_full(&pool, &bins, 1_000_000, true, 1_000).unwrap();
    assert_eq!(quote.amount_out, 2_677_765);
    assert_eq!(quote.fee, 10_000);
    assert_eq!(quote.protocol_fee, 500);
    assert_eq!(quote.pool_after.active_id, 100);
    assert_eq!(quote.pool_after.v_parameters.volatility_accumulator, 0);
    assert_eq!(quote.pool_after.v_parameters.index_reference, 100);
    assert_eq!(quote.pool_after.v_parameters.last_update_timestamp, 1_000);
}

#[test]
fn exact_in_three_bin_crossing() {
    // 3_000_000 X drains bins 100 and 99 and part of 98. The dynamic fee
    // climbs per bin crossed (accumulator 0 → 10_000 → 20_000), which is
    // why total fee (31_650) exceeds 3 × the flat 1% fee.
    let pool = preset(1, 0);
    let bins = [
        bin(98, 3 * B, 3 * B),
        bin(99, 3 * B, 3 * B),
        bin(100, 3 * B, 3 * B),
    ];
    let quote = compute_swap_full(&pool, &bins, 3_000_000, true, 1_000).unwrap();
    assert_eq!(quote.amount_out, 7_959_448);
    assert_eq!(quote.fee, 31_650);
    assert_eq!(quote.protocol_fee, 1_581);
    assert_eq!(quote.pool_after.active_id, 98);
    assert_eq!(quote.pool_after.v_parameters.volatility_accumulator, 20_000);
    assert_eq!(quote.pool_after.v_parameters.index_reference, 100);
}

#[test]
fn exact_in_crossing_upward() {
    // Y in, X out (!swap_for_y): the active bin walks up.
    let pool = preset(1, 0);
    let bins = [
        bin(100, 2 * B, 2 * B),
        bin(101, 2 * B, 2 * B),
        bin(102, 2 * B, 2 * B),
    ];
    let quote = compute_swap_full(&pool, &bins, 10_000_000, false, 1_000).unwrap();
    assert_eq!(quote.amount_out, 3_643_039);
    assert_eq!(quote.fee, 101_815);
    assert_eq!(quote.protocol_fee, 5_090);
    assert_eq!(quote.pool_after.active_id, 101);
    assert_eq!(quote.pool_after.v_parameters.volatility_accumulator, 10_000);
}

#[test]
fn exact_in_fee_on_output() {
    // collect_fee_mode = 1 (OnlyY) with swap_for_y: the fee lands on the
    // output (Y) side. The full input converts at the bin price, then the
    // fee is carved out of the output — a larger fee in Y units than the
    // fee-on-input case's fee in X units.
    let pool = preset(1, 1);
    let bins = [bin(100, 5 * B, 5 * B)];
    let quote = compute_swap_full(&pool, &bins, 1_000_000, true, 1_000).unwrap();
    assert_eq!(quote.amount_out, 2_677_764);
    assert_eq!(quote.fee, 27_049);
    assert_eq!(quote.protocol_fee, 1_352);
}

#[test]
fn exact_in_fills_limit_orders() {
    // function_type = 2 (LimitOrder). Bid-side orders (ask_side = 0) rest
    // in the active bin: MM liquidity (2M Y) fills first, then processed
    // orders, then open orders. The protocol fee is larger than the MM-only
    // case because the limit-order share of the fee is split 50/50 between
    // order placer and protocol (vs 5% protocol share on the MM part).
    let pool = preset(2, 0);
    let bins = [BinView {
        bin_id: 100,
        amount_x: 0,
        amount_y: 2 * B,
        price: get_price_from_id(100, 100).unwrap(),
        limit_order_ask_side: 0,
        open_order_amount: B,
        processed_order_remaining_amount: 500_000,
    }];
    let quote = compute_swap_full(&pool, &bins, 1_000_000, true, 1_000).unwrap();
    assert_eq!(quote.amount_out, 2_677_763);
    assert_eq!(quote.fee, 10_000);
    assert_eq!(quote.protocol_fee, 1_639);
    assert_eq!(quote.pool_after.active_id, 100);
}

#[test]
fn exact_in_warm_pool_decays_reference() {
    // Prior volatility (80_000) with 100s elapsed: inside the decay window,
    // so the reference decays to 40_000 and the accumulator climbs from
    // there per bin — the fee is roughly double the cold-pool crossing.
    let mut pool = preset(1, 0);
    pool.v_parameters.volatility_accumulator = 80_000;
    pool.v_parameters.index_reference = 103;
    pool.v_parameters.last_update_timestamp = 500;
    let bins = [
        bin(98, 3 * B, 3 * B),
        bin(99, 3 * B, 3 * B),
        bin(100, 3 * B, 3 * B),
    ];
    let quote = compute_swap_full(&pool, &bins, 3_000_000, true, 600).unwrap();
    assert_eq!(quote.amount_out, 7_886_528);
    assert_eq!(quote.fee, 59_151);
    assert_eq!(quote.protocol_fee, 2_956);
    assert_eq!(quote.pool_after.v_parameters.volatility_accumulator, 60_000);
    assert_eq!(quote.pool_after.v_parameters.volatility_reference, 40_000);
    assert_eq!(quote.pool_after.v_parameters.index_reference, 100);
}

#[test]
fn exact_in_pool_out_of_liquidity() {
    // More input than the supplied bins can absorb: the loop walks past the
    // last bin in the swap direction and errors, mirroring upstream's
    // bitmap-exhausted "Pool out of liquidity".
    let pool = preset(1, 0);
    let bins = [bin(99, B, B), bin(100, B, B)];
    assert_eq!(
        compute_swap_full(&pool, &bins, 10_000_000_000, true, 1_000).unwrap_err(),
        ErrorCode::PoolOutOfLiquidity,
    );
    // No bins at all: immediate out-of-liquidity, not a hang.
    assert_eq!(
        compute_swap_full(&pool, &[], 1, true, 1_000).unwrap_err(),
        ErrorCode::PoolOutOfLiquidity,
    );
}

#[test]
fn gap_bins_are_walked_through() {
    // A bin id absent from the slice is an empty bin: the swap walks
    // through the gap and fills from the far side. Totals must match the
    // same pool with the gap bin explicitly present but empty.
    let pool = preset(1, 0);
    let with_gap = [bin(97, 5 * B, 5 * B), bin(100, B, B)];
    let explicit = [
        bin(97, 5 * B, 5 * B),
        bin(98, 0, 0),
        bin(99, 0, 0),
        bin(100, B, B),
    ];
    let a = compute_swap_full(&pool, &with_gap, 2_000_000, true, 1_000).unwrap();
    let b = compute_swap_full(&pool, &explicit, 2_000_000, true, 1_000).unwrap();
    assert_eq!(a, b);
    assert_eq!(a.pool_after.active_id, 97);
}

#[test]
fn exact_out_single_bin() {
    // Request exactly 1_000_000 Y out: amount_in is fee-included.
    let pool = preset(1, 0);
    let bins = [bin(100, 5 * B, 5 * B)];
    let quote = compute_swap_full_exact_out(&pool, &bins, 1_000_000, true, 1_000).unwrap();
    assert_eq!(quote.amount_in, 373_447);
    assert_eq!(quote.fee, 3_735);
    assert_eq!(quote.protocol_fee, 188);
    assert_eq!(quote.pool_after.active_id, 100);
}

#[test]
fn exact_out_crossing_with_drain() {
    // 5_000_000 Y out of 3M-deep bins: bin 100 hits the drain-entire-bin
    // path, bin 99 fills the remainder exactly.
    let pool = preset(1, 0);
    let bins = [
        bin(98, 3 * B, 3 * B),
        bin(99, 3 * B, 3 * B),
        bin(100, 3 * B, 3 * B),
    ];
    let quote = compute_swap_full_exact_out(&pool, &bins, 5_000_000, true, 1_000).unwrap();
    assert_eq!(quote.amount_in, 1_875_004);
    assert_eq!(quote.fee, 19_053);
    assert_eq!(quote.protocol_fee, 952);
    assert_eq!(quote.pool_after.active_id, 99);
    assert_eq!(quote.pool_after.v_parameters.volatility_accumulator, 10_000);
}

#[test]
fn exact_out_resolves_lazy_price() {
    // A BinView with price = 0 (on-chain bin never touched): the exact-out
    // loop resolves it via get_or_store_bin_price — same quote as the
    // initialized-price bin.
    let pool = preset(1, 0);
    let mut lazy = bin(100, 5 * B, 5 * B);
    lazy.price = 0;
    let quote = compute_swap_full_exact_out(&pool, &[lazy], 1_000_000, true, 1_000).unwrap();
    assert_eq!(quote.amount_in, 373_447);
    assert_eq!(quote.fee, 3_735);
    assert_eq!(quote.protocol_fee, 188);
}

#[test]
fn exact_in_exact_out_round_trip() {
    // Feeding an exact-in quote's output into exact-out must reproduce the
    // original input and identical fees, bin-for-bin.
    let pool = preset(1, 0);
    let bins = [
        bin(98, 3 * B, 3 * B),
        bin(99, 3 * B, 3 * B),
        bin(100, 3 * B, 3 * B),
    ];
    let quote_in = compute_swap_full(&pool, &bins, 3_000_000, true, 1_000).unwrap();
    assert_eq!(quote_in.amount_out, 7_959_448);
    let quote_out =
        compute_swap_full_exact_out(&pool, &bins, quote_in.amount_out, true, 1_000).unwrap();
    assert_eq!(quote_out.amount_in, 3_000_000);
    assert_eq!(quote_out.fee, quote_in.fee);
    assert_eq!(quote_out.protocol_fee, quote_in.protocol_fee);
    assert_eq!(quote_out.pool_after, quote_in.pool_after);
}
