//! Value-pinned tests for `bin_math::get_price_from_id`.
//!
//! Expected prices were generated by an independent Python re-implementation
//! of the upstream MeteoraAg/dlmm-sdk `pow` + `get_price_from_id` algorithm.
//! Pinning the integer result (not just round-tripping through the function
//! under test) is what catches porting mistakes.

use solana_dlmm_meteora::bin_math::{get_price_from_id, ONE};
use solana_dlmm_meteora::{
    get_amount_in, get_amount_out, get_max_amount_in, get_max_amount_out, BinView, ErrorCode,
    Rounding, MAX_BIN_ID, MIN_BIN_ID,
};

#[test]
fn price_at_id_zero_is_q64_one() {
    // exp == 0 short-circuits; the result must be exactly 1.0 in Q64.64
    // regardless of bin_step.
    for bin_step in [1u16, 25, 100, 400] {
        assert_eq!(get_price_from_id(0, bin_step).unwrap(), ONE);
    }
    assert_eq!(ONE, 1u128 << 64);
}

#[test]
fn price_pinned_small_steps() {
    // (active_id, bin_step) → expected Q64.64 price.
    // Generated by an independent Python port of upstream's integer `pow`.
    let cases: &[(i32, u16, u128)] = &[
        (1, 100, 18_631_211_514_446_647_132),
        (-1, 100, 18_264_103_043_276_783_778),
        (100, 100, 49_895_008_478_369_174_654),
        (1000, 25, 224_027_336_091_247_007_920),
        (-1000, 25, 1_518_932_344_856_077_884),
    ];
    for &(id, step, expected) in cases {
        assert_eq!(
            get_price_from_id(id, step).unwrap(),
            expected,
            "mismatch at active_id={id}, bin_step={step}",
        );
    }
}

#[test]
fn price_at_bin_id_bounds() {
    // At ±MAX_BIN_ID with bin_step=1 (1bp), the price saturates at the edges
    // of u128: max bin → u128::MAX, min bin → 1 (smallest representable
    // non-zero). Pinning these locks the boundary contract upstream encodes
    // via MAX_EXPONENTIAL = 0x80000.
    assert_eq!(get_price_from_id(MAX_BIN_ID, 1).unwrap(), u128::MAX);
    assert_eq!(get_price_from_id(MIN_BIN_ID, 1).unwrap(), 1u128);
}

#[test]
fn bin_id_bounds_match_upstream() {
    // Sanity-pin upstream's `commons/src/constants.rs`.
    assert_eq!(MIN_BIN_ID, -443_636);
    assert_eq!(MAX_BIN_ID, 443_636);
}

#[test]
fn price_monotonic_around_zero() {
    // Cheap sanity: price strictly increases with active_id at any bin_step.
    // (Property tests over the full bin range live in a future milestone.)
    for &step in &[1u16, 10, 100, 400] {
        let prev = get_price_from_id(-5, step).unwrap();
        let mut last = prev;
        for id in -4..=5 {
            let p = get_price_from_id(id, step).unwrap();
            assert!(p > last, "non-monotonic at id={id}, step={step}");
            last = p;
        }
    }
}

// ---- swap_math (milestone 3 — structural per-bin primitives) ----
//
// Expected values pinned by an independent Python oracle of the upstream
// `mul_div` / `mul_shr` / `shl_div` algorithm. Same posture as the bin-math
// tests above: pin the integer result, not just round-trip.

#[test]
fn swap_step_identity_at_unit_price() {
    // price = ONE means 1 X == 1 Y. Every primitive should be the identity.
    for sfy in [true, false] {
        assert_eq!(
            get_amount_out(1000, ONE, sfy, Rounding::Down).unwrap(),
            1000
        );
        assert_eq!(get_amount_in(1000, ONE, sfy, Rounding::Up).unwrap(), 1000);
    }
}

#[test]
fn swap_step_at_price_two() {
    // price == 2.0 (Q64.64): 1 X buys 2 Y, equivalently 2 Y buys 1 X.
    let p = 2 * ONE;
    assert_eq!(get_amount_out(1000, p, true, Rounding::Down).unwrap(), 2000);
    assert_eq!(get_amount_out(1000, p, false, Rounding::Down).unwrap(), 500);
    assert_eq!(get_amount_in(2000, p, true, Rounding::Up).unwrap(), 1000);
    assert_eq!(get_amount_in(500, p, false, Rounding::Up).unwrap(), 1000);
}

#[test]
fn swap_step_rounding_sensitive() {
    // price = ONE + 1 stresses the rounding direction. amount_out rounds
    // down; amount_in rounds up. The 1-unit cases below are the smallest
    // inputs that produce a different rounding result for the two paths.
    let p = ONE + 1;
    assert_eq!(get_amount_out(1, p, true, Rounding::Down).unwrap(), 1);
    assert_eq!(get_amount_in(1, p, true, Rounding::Up).unwrap(), 1);
    assert_eq!(get_amount_out(1, p, false, Rounding::Down).unwrap(), 0);
    // 1 * (ONE + 1) >> 64 with ceil is 2, not 1: this is the ceil/floor
    // divergence the upstream contract requires.
    assert_eq!(get_amount_in(1, p, false, Rounding::Up).unwrap(), 2);
}

#[test]
fn swap_step_realistic_price() {
    // Use the price for (active_id=100, bin_step=100) — value pinned in
    // `price_pinned_small_steps` above. Sanity-check that get_amount_in
    // round-trips get_amount_out within a 1-unit rounding ulp.
    let p = get_price_from_id(100, 100).unwrap();
    assert_eq!(
        get_amount_out(1_000_000, p, true, Rounding::Down).unwrap(),
        2_704_813
    );
    assert_eq!(
        get_amount_out(1_000_000, p, false, Rounding::Down).unwrap(),
        369_711
    );
    // Round-trip: Y → required X → matches the original input.
    assert_eq!(
        get_amount_in(2_704_813, p, true, Rounding::Up).unwrap(),
        1_000_000
    );
    // Asymmetric direction returns a different value (this is the inverse
    // operation, not a round-trip).
    assert_eq!(
        get_amount_in(2_704_813, p, false, Rounding::Up).unwrap(),
        7_316_016
    );
}

#[test]
fn swap_step_max_amounts() {
    // Bin holding 10k X / 50k Y at price = 2.0. Confirms the bin reserves
    // are the cap on the output side and the price-converted equivalent
    // is the cap on the input side.
    let bin = BinView {
        bin_id: 0,
        amount_x: 10_000,
        amount_y: 50_000,
        ..BinView::default()
    };
    let p = 2 * ONE;
    assert_eq!(get_max_amount_out(&bin, true), 50_000);
    assert_eq!(get_max_amount_out(&bin, false), 10_000);
    assert_eq!(get_max_amount_in(&bin, p, true).unwrap(), 25_000);
    assert_eq!(get_max_amount_in(&bin, p, false).unwrap(), 20_000);
}

#[test]
fn swap_step_overflows_to_u64_cast_error() {
    // u64::MAX * 1.0 fits in u64; u64::MAX * 2.0 doesn't. The cast back
    // from u128 to u64 must surface as MathOverflow, not silently wrap.
    let p = 2 * ONE;
    assert_eq!(
        get_amount_out(u64::MAX, ONE, true, Rounding::Down).unwrap(),
        u64::MAX,
    );
    assert_eq!(
        get_amount_out(u64::MAX, p, true, Rounding::Down).unwrap_err(),
        ErrorCode::MathOverflow,
    );
}
